# DO NOT COMMIT THIS FILE WITH REAL VALUES!
# Use kubectl create secret or tools like sealed-secrets, external-secrets

# Create secrets using:
# kubectl create secret generic postgres-secret \
#   --from-literal=username=postgres \
#   --from-literal=password=YOUR_PASSWORD \
#   -n thesisapp

# kubectl create secret generic minio-secret \
#   --from-literal=access-key=minioadmin \
#   --from-literal=secret-key=YOUR_SECRET \
#   -n thesisapp

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: thesisapp
type: Opaque
stringData:
  username: postgres
  password: CHANGE_ME  # Change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: thesisapp
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: CHANGE_ME  # Change this!
---
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: thesisapp
type: Opaque
stringData:
  username: your-email@example.com
  password: CHANGE_ME  # Change this!
